In [1]:
from collections import Counter
from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("data/mushrooms.csv")
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
5        e         x           y         y       t    a               f   
6        e         b           s         w       t    a               f   
7        e         b           y         w       t    l               f   
8        p         x           y         w       t    p               f   
9        e         b           s         y       t    a               f   
10       e         x           y         y       t    l               f   
11       e         x           y         y       t    a               f   
12       e         b           s         y       t    a               f   
13       p         x           y         w       t    p               f   
14       e         x           f         n       f    n               f   
15       e         s           f         g       f    n               f   
16       e         f           f         w       f    n               f   
17       p         x           s         n       t    p               f   
18       p         x           y         w       t    p               f   
19       p         x           s         n       t    p               f   
20       e         b           s         y       t    a               f   
21       p         x           y         n       t    p               f   
22       e         b           y         y       t    l               f   
23       e         b           y         w       t    a               f   
24       e         b           s         w       t    l               f   
25       p         f           s         w       t    p               f   
26       e         x           y         y       t    a               f   
27       e         x           y         w       t    l               f   
28       e         f           f         n       f    n               f   
29       e         x           s         y       t    a               f   
...    ...       ...         ...       ...     ...  ...             ...   
8094     e         b           s         g       f    n               f   
8095     p         x           y         c       f    m               f   
8096     e         k           f         w       f    n               f   
8097     p         k           y         n       f    s               f   
8098     p         k           s         e       f    y               f   
8099     e         k           f         w       f    n               f   
8100     e         f           s         n       f    n               a   
8101     p         k           s         e       f    s               f   
8102     e         x           s         n       f    n               a   
8103     e         k           s         n       f    n               a   
8104     e         k           s         n       f    n               a   
8105     e         k           s         n       f    n               a   
8106     e         k           s         n       f    n               a   
8107     e         x           s         n       f    n               a   
8108     p         k           y         e       f    y               f   
8109     e         b           s         w       f    n               f   
8110     e         x           s         n       f    n               a   
8111     e         k           s         w       f    n               f   
8112     e         k           s         n       f    n               a   
8113     p         k           y         e       f    y               f   
8114     p         f           y         c       f    m               a   
8115     e         x          

In [3]:
labels_data = list(data["class"])
print(labels_data)

['p', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'p', 'p', 'p', 'e', 'p', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'p', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'p', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e',

In [4]:
labels = []
for label in labels_data:
    if label == "p":
        labels.append([0])
    elif label == "e":
        labels.append([1])
        
labels = np.array(labels)
labels.shape

(8124, 1)

In [5]:
data = data.drop(labels=["class"], axis=1)
data

cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
5            x           y         y       t    a               f   
6            b           s         w       t    a               f   
7            b           y         w       t    l               f   
8            x           y         w       t    p               f   
9            b           s         y       t    a               f   
10           x           y         y       t    l               f   
11           x           y         y       t    a               f   
12           b           s         y       t    a               f   
13           x           y         w       t    p               f   
14           x           f         n       f    n               f   
15           s           f         g       f    n               f   
16           f           f         w       f    n               f   
17           x           s         n       t    p               f   
18           x           y         w       t    p               f   
19           x           s         n       t    p               f   
20           b           s         y       t    a               f   
21           x           y         n       t    p               f   
22           b           y         y       t    l               f   
23           b           y         w       t    a               f   
24           b           s         w       t    l               f   
25           f           s         w       t    p               f   
26           x           y         y       t    a               f   
27           x           y         w       t    l               f   
28           f           f         n       f    n               f   
29           x           s         y       t    a               f   
...        ...         ...       ...     ...  ...             ...   
8094         b           s         g       f    n               f   
8095         x           y         c       f    m               f   
8096         k           f         w       f    n               f   
8097         k           y         n       f    s               f   
8098         k           s         e       f    y               f   
8099         k           f         w       f    n               f   
8100         f           s         n       f    n               a   
8101         k           s         e       f    s               f   
8102         x           s         n       f    n               a   
8103         k           s         n       f    n               a   
8104         k           s         n       f    n               a   
8105         k           s         n       f    n               a   
8106         k           s         n       f    n               a   
8107         x           s         n       f    n               a   
8108         k           y         e       f    y               f   
8109         b           s         w       f    n               f   
8110         x           s         n       f    n               a   
8111         k           s         w       f    n               f   
8112         k           s         n       f    n               a   
8113         k           y         e       f    y               f   
8114         f           y         c       f    m               a   
8115         x           s         n       f    n               a   
8116         k           y         n       f    s               f   
8117         k           s         e       f    y               f   
8118         k           y         n       f    f               f   
8119         k           s         n       f    n               a   
812

In [6]:
data_test_matrix = []

for column in data.columns:
    column_data = []
    column_values = list(data[column])
    
    counter = Counter(column_values)
    n_column_labels = len(counter)
    column_labels = list(counter.keys())
    
    for i in range(n_column_labels):
        column_data.append(np.zeros(len(column_values)))
        
    for j in range(len(column_values)):
        label_index = column_labels.index(column_values[j])
        column_data[label_index][j] = 1
        
    for data_column in column_data:
        data_test_matrix.append(data_column)
        
data_test_matrix = np.array(data_test_matrix).transpose()
data_test_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [7]:
data_test_matrix.shape

(8124, 117)

In [8]:
s = np.arange(data_test_matrix.shape[0])
np.random.shuffle(s)
s

array([8083, 7332, 7400, ..., 3932, 2975, 6801])

In [9]:
data_test_matrix_shuffled = data_test_matrix[s]
data_test_matrix_shuffled

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [10]:
labels_shuffled = labels[s]
labels_shuffled

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [11]:
data_split = 0.1
split_instances = round(data_test_matrix_shuffled.shape[0] * data_split)
training_instances = data_test_matrix_shuffled.shape[0] - split_instances * 2
print("Training instances: {}".format(training_instances))
print("Split instances: {}".format(split_instances))

Training instances: 6500
Split instances: 812


In [12]:
training_data = data_test_matrix_shuffled[:training_instances, :]
training_labels = labels_shuffled[:training_instances, :]
training_data.shape

(6500, 117)

In [13]:
validation_data = data_test_matrix_shuffled[training_instances:training_instances + split_instances, :]
validation_labels = labels_shuffled[training_instances:training_instances + split_instances, :]
validation_data.shape

(812, 117)

In [14]:
test_data = data_test_matrix_shuffled[training_instances + split_instances:training_instances + split_instances * 2, :]
test_labels = labels_shuffled[training_instances + split_instances:training_instances + split_instances *2, :]
test_data.shape

(812, 117)

In [15]:
Path("training_data").mkdir(exist_ok=True)
np.save(open("training_data/mushrooms_training_data.npy", 'wb'), training_data)
np.save(open("training_data/mushrooms_training_labels.npy", 'wb'), training_labels)
np.save(open("training_data/mushrooms_validation_data.npy", 'wb'), validation_data)
np.save(open("training_data/mushrooms_validation_labels.npy", 'wb'), validation_labels)
np.save(open("training_data/mushrooms_test_data.npy", 'wb'), test_data)
np.save(open("training_data/mushrooms_test_labels.npy", 'wb'), test_labels)